MPI_model/MPI_model/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from django.conf.urls import url
# from accounts.views import index

# urlpatterns = [
#     url(r'^$', index),
#     url(r'login/', include('accounts.urls')),
#     url(r'patients/', include('patients.urls'))
# ]

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # path('', include('accounts.urls', 'accounts')),
    # path('accounts/', include('accounts.urls')),
    # path('patients/', include('patients.urls')),
    # path('prediction/', include('prediction.urls')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('patients', include(('patients.urls', 'patients'), namespace='patients')),
    path('prediction', include(('prediction.urls', 'prediction'), namespace='prediction')),
]

MPI_model/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.login_request, name="user_login"),
    url(r'^logout$', views.logout_request, name="logout"),
]

MPI_model/patients/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.patientList, name="patient_list"),
    url(r'^/addpatient$', views.addpatient, name="add_patient"),
    url(r'^/patientinfo/$', views.patientInfo, name="patient_info"),
]

MPI_model/prediction/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.prediction, name="predict"),
    url(r'/addpredict$', views.addPredict, name="add_predict"),
    url(r'/predict$', views.predict, name="predict_process"),
]

MPI_model/prediction/models.py
from django.db import models

# Create your models here.

MPI_model/prediction/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from patients.models import patients, patient_info
from django.contrib.auth.decorators import login_required
import pickle

#time
import pytz
from datetime import datetime, timezone

@login_required(login_url='accounts:user_login')
def prediction(request):
    if request.method == 'POST':
        print(request)
        no = int(request.GET.get('no'))
        patient_id = patients.objects.filter(patient_info__no = no)[0].pid
        method = request.POST.get('_method')
        print(method)
        if method == 'Save' :
            CAG_confirm = request.POST.get('CAG_confirm')
            if CAG_confirm != patient_info.objects.get(no = no).CAG_confirm :
                print("Update CAG_confirm of No : " + str(no))
                print("Old : " + str(patient_info.objects.get(no = no).CAG_confirm) + " New : " + str(CAG_confirm))
                patient_info.objects.filter(no = no).update(CAG_confirm = CAG_confirm)
            context = {
            'patient': patients.objects.get(pid = patient_id),
            'patient_info': patient_info.objects.get(no = no),
            'user_login' : request.user.username
            }
            return render(request, 'prediction.html', context)
        else :
            print("Delete No : " + str(no))
            patient_info.objects.filter(no = no).delete()
            context = {
                'patient': patients.objects.get(pid = patient_id),
                'patient_info': list(patient_info.objects.filter(pid = patient_id)),
                'user_login' : request.user.username
            }
            return render(request, 'patient_info.html', context)

    else :
        utc_dt = datetime.now(timezone.utc)
        BKK = pytz.timezone('Asia/Bangkok')
        # print("BKK time   {}".patient_info.objects.filter(patient_info__no = no)[0].pid)
        
        no = int(request.GET.get('no'))
        patient_id = patients.objects.filter(patient_info__no = no)[0].pid
        date = (patient_info.objects.filter(no = no)[0].date).now().date

        print("No = " + str(no))
        print("pid = " + str(patient_id))
        context = {
            'patient': patients.objects.get(pid = patient_id),
            'date' : date,
            'patient_info': patient_info.objects.get(no = no),
            'user_login' : request.user.username
        }
        return render(request, 'prediction.html', context)

@login_required(login_url='accounts:user_login')
def addPredict(request):
    if request.method == 'POST':
        
        #time zone
        utc_dt = datetime.now(timezone.utc)
        BKK = pytz.timezone('Asia/Bangkok')
        print("BKK time   {}".format(utc_dt.astimezone(BKK).astimezone()))
        print(request)
        
        patient_id =  int(request.POST.get('pid'))
        print("Add Info pid = " + str(patient_id))
        
        patientInfo = patient_info()
        patientInfo.age = request.POST.get('age')
        patientInfo.date2 = format(utc_dt.astimezone(BKK).astimezone())
        patientInfo.BMI = request.POST.get('bmi')
        patientInfo.DM = request.POST.get('dm')
        patientInfo.HT = request.POST.get('ht')
        patientInfo.DLP = request.POST.get('dlp')
        patientInfo.CKD = request.POST.get('ckd')
        patientInfo.LAD4dmspect = request.POST.get('lad_4dmspect')
        patientInfo.LADwallthick = request.POST.get('lad_wallthick')
        patientInfo.LADwallmotion = request.POST.get('lad_wallmotion')
        patientInfo.LCX4dmspect = request.POST.get('lcx_4dmspect')
        patientInfo.LCXwallthick = request.POST.get('lcx_wallthick')
        patientInfo.LCXwallmotion = request.POST.get('lcx_wallmotion')
        patientInfo.RCA4dmspect = request.POST.get('rca_4dmspect')
        patientInfo.RCAwallthick = request.POST.get('rca_wallthick')
        patientInfo.RCAwallmotion = request.POST.get('rca_wallmotion')
        patientInfo.LVEF = request.POST.get('lvef')
        patientInfo.CAG = request.POST.get('CAG')
        patientInfo.pid = patients.objects.get(pid = patient_id)
        patientInfo.save()
        
        no = int(patient_info.objects.latest('no').no)
        return HttpResponseRedirect('/prediction?no='+str(no))
    else :
        print(request)
        patient_id =  int(request.GET.get('pid'))
        print("pid = " + str(patient_id))
        context = {
            'patient': patients.objects.get(pid = patient_id),
            'user_login' : request.user.username
        }
        return render(request, 'addprediction.html', context)

@login_required(login_url='accounts:user_login')
def predict(request):
    ls_data = [1]
    if(request.method == 'POST'):
        pid = request.POST.get('pid')
        #MPI feature 
        #LAD
        lad_4dmspect = float(request.POST.get('lad_4dmspect'))
        lad_wallthick = float(request.POST.get('lad_wallthick'))
        lad_wallmotion = float(request.POST.get('lad_wallmotion'))

        #LCX
        lcx_4dmspect = float(request.POST.get('lcx_4dmspect'))
        lcx_wallthick = float(request.POST.get('lcx_wallthick'))
        lcx_wallmotion = float(request.POST.get('lcx_wallmotion'))
        
        #RCA
        rca_4dmspect = float(request.POST.get('rca_4dmspect'))
        rca_wallthick = float(request.POST.get('rca_wallthick'))
        rca_wallmotion = float(request.POST.get('rca_wallmotion'))
        
        lvef = float(request.POST.get('lvef'))
        
        #model
        data = [lad_4dmspect, lad_wallthick, lad_wallmotion, lcx_4dmspect, lcx_wallthick, lcx_wallmotion, rca_4dmspect, rca_wallthick, rca_wallmotion, lvef]
        ls_data[0] = data
        
        #load model
        file_d = open("static/model/model_mpi", "rb")
        model = pickle.load(file_d)
        print("data :", ls_data)

        #predict
        result = model.predict(ls_data)
        print("result CAG : ", result[0])
        
        #update request
        post = request.POST.copy() # to make it mutable
        post['CAG'] = str(result[0])
        request.POST = post

        file_d.close
        addPredict(request)
        no = int(patient_info.objects.latest('no').no)
    return HttpResponseRedirect('/prediction?no='+str(no))

MPI_model/prediction/templates/addprediction.html
{% extends 'prediction_base.html' %}
{% block content %}
        <div class="container">
          <div class="card o-hidden border-0 shadow-lg">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-12">
                  <div class="p-5">
                    <div class="text-center">
                      <h1 class="h4 font-weight-bold text-gray-900 mb-4">Examination</h1>
                    </div>

                    <div>
                      <h5 class="m-0 font-weight-bold text-gray-900 mb-4">Patient Characteristic</h5>
                    </div>
                  
                    <form class="user" method="post" action="{% url 'prediction:predict_process' %}">
                    {% csrf_token %}
                    <input type="hidden" value="{{patient.pid}}" name="pid">
                    <input type="hidden" value="0" name="CAG">
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        HN : {{ patient.HN }}
                      </div>
                      </div>

                      <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                          First Name : {{ patient.fname }}
                        </div>
                        <div class="col-sm-6">
                          Last Name : {{ patient.lname }}
                        </div>
                      </div>

                      <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                          Gender : {% if patient.gender == 0 %} Male
                          {% else %} Female
                          {% endif %}
                        </div>
                        <div class="col-sm-1">
                          Age :
                        </div>
                        <div class="col-sm-1.5">
                          <input class="form-control" type="number" id="age" name="age" min="1" max="100" required>
                        </div>
                      </div>

                      <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0">
                          <thead>
                            <tr>
                              <th>BMI</th>
                              <th>DM</th>
                              <th>HT</th>
                              <th>DLP</th>
                              <th>CKD</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>
                                <input class="form-control" type="number" step="0.01" id="bmi" name="bmi" required>
                              </td>
                              <td>
                                <select class="form-control" name="dm">
                                  <option value="0">Negative</option>
                                  <option value="1">Positive</option>
                                </select>
                              </td>
                              <td>
                                <select class="form-control" name="ht">
                                  <option value="0">Negative</option>
                                  <option value="1">Positive</option>
                                </select>
                              </td>
                              <td>
                                <select class="form-control" name="dlp">
                                  <option value="0">Negative</option>
                                  <option value="1">Positive</option>
                                </select>
                              </td>
                              <td>
                                <select class="form-control" name="ckd">
                                  <option value="0">Negative</option>
                                  <option value="1">Positive</option>
                                </select>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>

                      <br>
                      <div>
                        <h5 class="m-0 font-weight-bold text-gray-900 mb-4">MPI features</h5>
                      </div>

                      <div class="table-responsive">
                        <table class="table table-bordered" width="70%" cellspacing="0">
                          <thead>
                            <tr>
                              <th></th>
                              <th>4D-MSPECT</th>
                              <th>Wall Thickness</th>
                              <th>Wall Motion</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>LAD</td>
                              <td><input class="form-control" type="number" step="0.01" id="lad_4dmspect"
                                  name="lad_4dmspect" required></td>
                              <td><input class="form-control" type="number" step="0.01" id="lad_wallthick"
                                  name="lad_wallthick" required></td>
                              <td><input class="form-control" type="number" step="0.01" id="lad_wallmotion"
                                  name="lad_wallmotion" required></td>
                            </tr>
                            <tr>
                              <td>LCX</td>
                              <td><input class="form-control" type="number" step="0.01" id="lcx_4dmspect"
                                  name="lcx_4dmspect" required></td>
                              <td><input class="form-control" type="number" step="0.01" id="lcx_wallthick"
                                  name="lcx_wallthick" required></td>
                              <td><input class="form-control" type="number" step="0.01" id="lcx_wallmotion"
                                  name="lcx_wallmotion" required></td>
                            </tr>
                            <tr>
                              <td>RCA</td>
                              <td><input class="form-control" type="number" step="0.01" id="rca_4dmspect"
                                  name="rca_4dmspect" required></td>
                              <td><input class="form-control" type="number" step="0.01" id="rca_wallthick"
                                  name="rca_wallthick" required></td>
                              <td><input class="form-control" type="number" step="0.01" id="rca_wallmotion"
                                  name="rca_wallmotion" required></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>

                      <div class="form-group row">
                        <div class="col-sm-1">
                          LVEF :
                        </div>
                        <div class="col-sm-2">
                          <input class="form-control" type="number" id="lvef" name="lvef" min="1" max="100" required>
                        </div>
                      </div>
                    </div>
                    
                    <!-- Button -->
                    <br>
                    <a>
                      <button class="btn btn-primary btn-user btn-block" type="button" data-toggle="modal" data-target="#addPredictModal">Predict</button>
                      <!-- <input class="btn btn-primary btn-user btn-block" type="submit" value="Predict"> -->
                    </a>

                    <!-- Add Patient Modal-->
                      <div class="modal fade" id="addPredictModal" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Do you want to add this information?</h5>
                              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                              </button>
                            </div>
                            <div class="modal-body">Select "Save" below if you are want to predict.</div>
                            <div class="modal-footer">
                              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                              <a href="patients:patientinfo">
                                <input type="submit" name="" value="Save" class="btn btn-primary">
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

MPI_model/prediction/templates/prediction_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HEART MIBI</title>

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
  

</head>

<body id="page-top">
  
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'patients:patient_list'%}" style="margin: 1em">
        <div class="sidebar-brand-text mx-3">
          <img src="{% static 'img/logo.png' %}" height="60" width="210">
        </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <li class="nav-item">
        <a class="nav-link" href="/patients/addpatient">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Add Patient</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <li class="nav-item">
        <a class="nav-link" href="/patients">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Patient List</span></a>
      </li>

      <!-- Divider -->
      <!-- <hr class="sidebar-divider my-0">

      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Prediction</span></a>
      </li> -->

      <!-- Divider -->
      
      <hr class="sidebar-divider d-none d-md-block">
      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <!-- Account -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user_login }}</span>
                <img class="img-profile rounded-circle" src="{% static 'img/doctor.png'%}">
              </a>
              <!-- Dropdown -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'accounts:logout' %}" data-toggle="modal"
                  data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
            {% endif %}

          </ul>

        </nav>
        <!-- End of Topbar -->

        {% block content %}
        {% endblock %}
      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>